### ISSUE TITLE
I can't select all rows in the table

### ISSUE THREAD

**Issue by igorquinta** [imbus/robotframework-robosapiens#6]
As described in the title, I cannot select all rows from a shell table. I've already tried using "Select Table Row 0" but it only selects the first 2 rows.

I also tried clicking the button that selects all lines but without success, could anyone help me?

![image](https://github.com/user-attachments/assets/2229b8e1-1711-4124-8299-bc9f2034adf8)

I use version RoboSAPiens 2.9.3

**Comment by kriffx** [comment]
It's not the best way, but I did it like this:
```
Select Cell    row_locator=1    column=Status
Press Keys    left
Press Key Combination    key_combination=Enter
```

**Comment by mardukbp** [comment]
> I've already tried using "Select Table Row 0" but it only selects the first 2 rows.
You are right. I got that hint from a user. I guess they tried it with a table with only two rows. I will remove it from the documentation.

In some ALV Grids (the user-friendly name of GuiShell: GuiGridView) the context menu obtained with the secondary mouse button contains an entry "Select All" with the keyboard shortcut F9. If that is your case, you could call `Press Key Combination    F9`.

In order to have a general solution I will implement a new keyword that calls the method SelectAll of GuiGridView. Give me a few days.

@kriffx That's a neat trick :) `Select Table Row   1` did not work for you?

**Comment by kriffx** [comment]
@mardukbp Thank you for your feedback, the keyword you gave me really worked, in my case it is just one line that appears in this table, my problem was not the same as the colleague in this issue, as I solved it in a different way, this did not prevent me from executing the script, but having the correct keyword makes me more satisfied.

**Comment by igorquinta** [comment]
@mardukbp Thank you very much for your feedback, for now I solved it using the "SapGuiLybrary". Using F9 also didn't work, as soon as "Select all" is implemented I will definitely use it.

![image](https://github.com/user-attachments/assets/3fa88712-1da8-4367-a4ee-c53cfcc52c46)

@kriffx To select just one row, "Select table row" works great, but in this case I couldn't select all the rows.

**Comment by mardukbp** [comment]
In the end I changed the implementation of the keyword so that `Select Table Row   0` actually selects the whole table, as stated in the documentation. Please try again with version 2.10.1.

**Comment by igorquinta** [comment]
@mardukbp it worked perfectly, thank you for your feedback and attention, a hug from Brazil.
